export const JOB_CATEGORIES = {
  limpieza: { label: "Limpieza", icon: "Sparkles" },
  reparaciones: { label: "Reparaciones", icon: "Wrench" },
  mudanzas: { label: "Mudanzas", icon: "Truck" },
  jardineria: { label: "Jardinería", icon: "TreePine" },
  cuidado_personas: { label: "Cuidado de personas", icon: "Heart" },
  clases: { label: "Clases particulares", icon: "GraduationCap" },
  tecnologia: { label: "Tecnología", icon: "Laptop" },
  otros: { label: "Otros", icon: "MoreHorizontal" },
} as const;

export const PROVINCES = {
  alava: "Álava",
  albacete: "Albacete",
  alicante: "Alicante",
  almeria: "Almería",
  asturias: "Asturias",
  avila: "Ávila",
  badajoz: "Badajoz",
  barcelona: "Barcelona",
  burgos: "Burgos",
  caceres: "Cáceres",
  cadiz: "Cádiz",
  cantabria: "Cantabria",
  castellon: "Castellón",
  ciudad_real: "Ciudad Real",
  cordoba: "Córdoba",
  cuenca: "Cuenca",
  girona: "Girona",
  granada: "Granada",
  guadalajara: "Guadalajara",
  guipuzcoa: "Guipúzcoa",
  huelva: "Huelva",
  huesca: "Huesca",
  islas_baleares: "Islas Baleares",
  jaen: "Jaén",
  la_coruna: "La Coruña",
  la_rioja: "La Rioja",
  las_palmas: "Las Palmas",
  leon: "León",
  lleida: "Lleida",
  lugo: "Lugo",
  madrid: "Madrid",
  malaga: "Málaga",
  murcia: "Murcia",
  navarra: "Navarra",
  ourense: "Ourense",
  palencia: "Palencia",
  pontevedra: "Pontevedra",
  salamanca: "Salamanca",
  santa_cruz_tenerife: "Santa Cruz de Tenerife",
  segovia: "Segovia",
  sevilla: "Sevilla",
  soria: "Soria",
  tarragona: "Tarragona",
  teruel: "Teruel",
  toledo: "Toledo",
  valencia: "Valencia",
  valladolid: "Valladolid",
  vizcaya: "Vizcaya",
  zamora: "Zamora",
  zaragoza: "Zaragoza",
  ceuta: "Ceuta",
  melilla: "Melilla",
} as const;

export const JOB_STATUS = {
  open: { label: "Abierto", color: "success" },
  assigned: { label: "Asignado", color: "info" },
  approved: { label: "Aprobado", color: "warning" },
  completed: { label: "Completado", color: "muted" },
  cancelled: { label: "Cancelado", color: "destructive" },
} as const;

export type JobCategory = keyof typeof JOB_CATEGORIES;
export type Province = keyof typeof PROVINCES;
export type JobStatus = keyof typeof JOB_STATUS;
